/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:17152c0a-12e0-41e3-b683-ab663af426aa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RhEO8a1eE",
    "aws_user_pools_web_client_id": "16i9mtdu9ib9vls4c7hfs2nuel",
    "oauth": {}
};


export default awsmobile;
